# Generated by Django 4.1.2 on 2022-12-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0002_alter_pap_compensationstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labourcamp',
            old_name='LabourCampTitle',
            new_name='LabourCampID',
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='distanceFromSite',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='labourcamp_documents/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='labourCampName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='modeOfTransportation',
            field=models.CharField(blank=True, choices=[('public', 'public'), ('private', 'private')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='photographs',
            field=models.ImageField(blank=True, null=True, upload_to='labourcamp_photographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pap',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='PAP_documents/'),
        ),
        migrations.AddField(
            model_name='pap',
            name='photographs',
            field=models.ImageField(blank=True, null=True, upload_to='PAP_photographs/'),
        ),
        migrations.AddField(
            model_name='pap',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
