# Generated by Django 4.1.2 on 2022-12-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0003_rename_labourcamptitle_labourcamp_labourcampid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pap',
            old_name='dateOfNotification',
            new_name='dateOfIdentification',
        ),
        migrations.AddField(
            model_name='pap',
            name='addressOfPAP',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pap',
            name='dateOfRehabilitation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pap',
            name='legalDocuments',
            field=models.FileField(blank=True, null=True, upload_to='PAP_legalDocuments/'),
        ),
        migrations.AddField(
            model_name='pap',
            name='nameOfPAP',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pap',
            name='typeOfCashCompensation',
            field=models.CharField(blank=True, choices=[('2.5 x Area', '2.5 x Area'), ('Money', 'Money'), ('Both', 'Both')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pap',
            name='ownershipStatus',
            field=models.CharField(blank=True, choices=[('Flat/House', 'Flat/House'), ('Land', 'Land'), ('Independant House/ Hutment', 'Independant House/ Hutment'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
