# Generated by Django 4.1.2 on 2022-12-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0004_rename_dateofnotification_pap_dateofidentification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pap',
            name='isLivelihoodSupport',
            field=models.BooleanField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
