# Generated by Django 4.1.2 on 2022-12-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0005_alter_pap_islivelihoodsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='pap',
            name='otherCompensationType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pap',
            name='papId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pap',
            name='typeOfCashCompensation',
            field=models.CharField(blank=True, choices=[('2.5 x Area', '2.5 x Area'), ('Money', 'Money'), ('Both', 'Both'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
