# Generated by Django 4.1.2 on 2022-12-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0006_pap_othercompensationtype_pap_papid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pap',
            old_name='ownershipStatus',
            new_name='typeOfStructure',
        ),
    ]
