# Generated by Django 4.1.2 on 2022-12-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0007_rename_ownershipstatus_pap_typeofstructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pap',
            name='addressOfPAP',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pap',
            name='categoryOfPap',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Commercial', 'Commercial'), ('Land', 'Land'), ('Institutional', 'Institutional'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pap',
            name='typeOfStructure',
            field=models.CharField(blank=True, choices=[('Flat/House', 'Flat/House'), ('Land', 'Land'), ('Independent House/Hutment', 'Independent House/Hutment'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
