# Generated by Django 4.1.2 on 2022-12-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0008_alter_pap_addressofpap_alter_pap_categoryofpap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsitedetails',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='constructionsite_documents/'),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='photographs',
            field=models.ImageField(blank=True, null=True, upload_to='constructionsite_photographs/'),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
