# Generated by Django 4.1.2 on 2022-12-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0009_constructionsitedetails_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionsitedetails',
            name='sitephotographs',
        ),
    ]
