# Generated by Django 4.1.2 on 2022-12-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0011_labourcamp_sourceofwater_labourcamp_waterdisposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehabilation',
            name='PAP_id',
        ),
        migrations.DeleteModel(
            name='Compensation',
        ),
        migrations.DeleteModel(
            name='Rehabilation',
        ),
    ]
