# Generated by Django 4.1.2 on 2022-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0012_remove_rehabilation_pap_id_delete_compensation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourcamp',
            name='DemarkingOfPathwaysCondition',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='drinkingWaterCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='fireExecutionCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='kitchenAreaCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='roomsOrDomsCondition',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Shared Rooms', 'Shared Rooms')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='segregationOfwasteCondition',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='signagesLabelingCondition',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='toiletCondition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='transportationFacilityCondition',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Required', 'Not Required')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='isToilet',
            field=models.BooleanField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255),
        ),
    ]
