# Generated by Django 4.1.2 on 2022-12-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0013_labourcamp_demarkingofpathwayscondition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labourcamp',
            old_name='isDemarkingOfPathways',
            new_name='isDemarkationOfPathways',
        ),
        migrations.RemoveField(
            model_name='labourcamp',
            name='DemarkingOfPathwaysCondition',
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='isToilet',
            field=models.BooleanField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='toiletCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
    ]
