# Generated by Django 4.1.5 on 2024-01-16 07:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0014_rename_typeofasset_pap_typeofstructure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectaffectedperson',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('pap_id', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'projectAffectedPerson',
                'managed': False,
            },
        ),
    ]
