# Generated by Django 4.1.5 on 2024-01-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0015_projectaffectedperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='pap',
            name='firstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pap',
            name='lastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
