# Generated by Django 4.1.2 on 2022-12-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0015_rename_dateofconduct_constructionsitedetails_dateofmonitoring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourcamp',
            name='isFireExecution',
        ),
        migrations.RemoveField(
            model_name='labourcamp',
            name='photographs',
        ),
        migrations.RemoveField(
            model_name='labourcamp',
            name='sourceOfWater',
        ),
        migrations.RemoveField(
            model_name='labourcamp',
            name='waterDisposal',
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='GenralPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='Labour Camp/GenralPhotographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='availabilityOfDoctorCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='availabilityOfDoctorPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='Labour Camp/AvailabilityOfDoctor_photographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='availabilityOfDoctorRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='demarkationOfPathwaysCondition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='demarkationOfPathwaysPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='Labour Camp/demarkingPathways_photographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='demarkationOfPathwaysRemark',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='drinkingWaterPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='Labour Camp/drinkingWater_photographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='drinkingWaterRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='fireExtinguishPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='Labour Camp/fireExtinguish_photographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='fireExtinguishRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='firstAidKitCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='firstAidKitPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='Labour Camp/FirstAidKit_photographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='firstAidKitRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='isFireExtinguish',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='kitchenAreaPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='Labour Camp/KitchenArea _photographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='kitchenAreaRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='regularHealthCheckupCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='regularHealthCheckupPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='Labour Camp/RegularHealthCheckup_Photographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='regularHealthCheckupRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='roomsOrDomsPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='Labour Camp/rooms_photographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='roomsOrDomsRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='segregationOfwastePhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='labour Camp/segrigationOfWaste_Photographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='segregationOfwasteRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='signagesLabelingCondition',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='signagesLabelingPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='Labour Camp/signagesLabeling_Photographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='signagesLabelingRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='toiletPhotograph',
            field=models.ImageField(blank=True, null=True, upload_to='Labour Camp/toilet_photographs/'),
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='toiletRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='drinkingWaterCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='isKitchenArea',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='isRoomsOrDoms',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='modeOfTransportation',
            field=models.CharField(blank=True, choices=[('Arranged By Contractor', 'Arranged By Contractor'), ('Arranged By MMRDA', 'Arranged By MMRDA')], max_length=255, null=True),
        ),
    ]
