# Generated by Django 4.1.5 on 2024-01-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0016_pap_firstname_pap_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabilitation',
            name='firstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='lastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
