# Generated by Django 4.1.2 on 2022-12-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0016_remove_labourcamp_isfireexecution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labourcamp',
            old_name='fireExecutionCondition',
            new_name='fireExtinguishCondition',
        ),
    ]
