# Generated by Django 4.1.2 on 2022-12-31 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0017_rename_fireexecutioncondition_labourcamp_fireextinguishcondition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pap',
            old_name='papId',
            new_name='PAPID',
        ),
        migrations.RenameField(
            model_name='pap',
            old_name='addressOfPAP',
            new_name='addressLine1',
        ),
        migrations.RenameField(
            model_name='pap',
            old_name='isEngagementType',
            new_name='streetName',
        ),
        migrations.RenameField(
            model_name='pap',
            old_name='typeOfStructure',
            new_name='typeOfAsset',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='compensationStatus',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='dateOfRehabilitation',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='isCommunityEngagement',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='isLivelihoodSupport',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='isShiftingAllowance',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='isTenaments',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='isTraining',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='isTransportationAllowance',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='isfinancialSupport',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='otherCompensationType',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='photographs',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='rehabilitationStatus',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='typeOfCashCompensation',
        ),
        migrations.AddField(
            model_name='pap',
            name='GovernmentLand',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pap',
            name='individualLandAsset',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pap',
            name='notAgreedReason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pap',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pap',
            name='presentPhotograp',
            field=models.ImageField(blank=True, null=True, upload_to='PAP/presentphotograph'),
        ),
        migrations.AddField(
            model_name='pap',
            name='privateLand',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pap',
            name='categoryOfPap',
            field=models.CharField(blank=True, choices=[('Individual / Joint Holding', 'Individual / Joint Holding'), ('Commercial', 'Commercial'), ('Private Land', 'Private Land'), ('Government Land', 'Government Land'), ('Institutional', 'Institutional'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pap',
            name='eligibility',
            field=models.CharField(blank=True, choices=[('Eligible', 'eligible'), ('Not eligible', 'Not eligible'), ('Pending', 'Pending')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pap',
            name='legalDocuments',
            field=models.FileField(blank=True, null=True, upload_to='PAP/PAP_legalDocuments/'),
        ),
        migrations.AlterField(
            model_name='pap',
            name='legalStatus',
            field=models.CharField(blank=True, choices=[('legal', 'legal'), ('illegal', 'illegal'), ('under dispute', 'under dispute')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Rehabilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfRehabilitation', models.DateField(blank=True, null=True)),
                ('PAPName', models.CharField(blank=True, max_length=255, null=True)),
                ('cashCompensation', models.PositiveIntegerField(blank=True, null=True)),
                ('compensationStatus', models.CharField(blank=True, choices=[('Cash Compensation', 'Cash Compensation'), ('Land Provided Assets', 'Land Provided Assets'), ('Alternate accommodation', 'Alternate accommodation'), ('Commercial Unit', 'Commercial Unit')], max_length=255, null=True)),
                ('typeOfCompensation', models.CharField(blank=True, choices=[('2.5 x Area', '2.5 x Area'), ('Cash', 'Cash'), ('Both', 'Both'), ('Other', 'Other')], max_length=255, null=True)),
                ('otherCompensationType', models.CharField(blank=True, max_length=255, null=True)),
                ('addressLine1', models.TextField(blank=True, max_length=255, null=True)),
                ('streetName', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.BigIntegerField(blank=True, null=True)),
                ('isShiftingAllowance', models.BooleanField(blank=True)),
                ('shiftingAllowanceAmount', models.IntegerField(blank=True)),
                ('isLivelihoodSupport', models.BooleanField(blank=True)),
                ('livelihoodSupportCondition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True)),
                ('livelihoodSupportPhotograph', models.ImageField(blank=True, null=True, upload_to='', verbose_name='rehabitation/livelihoodSupportPhotograph/')),
                ('livelihoodSupportRemarks', models.TextField(blank=True, max_length=255, null=True)),
                ('isTraining', models.BooleanField(blank=True)),
                ('trainingCondition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True)),
                ('trainingPhotograph', models.ImageField(blank=True, upload_to='', verbose_name='rehabitation/trainingPhotograph/')),
                ('trainingRemarks', models.TextField(blank=True, max_length=255, null=True)),
                ('isTenaments', models.BooleanField(blank=True)),
                ('tenamentsCondition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True)),
                ('tenamentsPhotograph', models.ImageField(blank=True, null=True, upload_to='', verbose_name='rehabitation/tenamentsPhotograph/')),
                ('tenamentsRemarks', models.TextField(blank=True, max_length=255, null=True)),
                ('isRelocationAllowance', models.BooleanField(blank=True)),
                ('RelocationAllowanceAmount', models.PositiveIntegerField(blank=True)),
                ('isfinancialSupport', models.BooleanField(blank=True)),
                ('financialSupportAmount', models.PositiveIntegerField(blank=True)),
                ('isCommunityEngagement', models.BooleanField(blank=True)),
                ('isEngagementType', models.CharField(blank=True, max_length=255, null=True)),
                ('photographs', models.ImageField(blank=True, null=True, upload_to='rehabitation/Rehabitationphotographs/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='rehabitation/documents')),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('PAPID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehabilitation', to='SocialMonitoring.pap')),
            ],
        ),
    ]
