# Generated by Django 4.1.2 on 2022-12-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0018_rename_papid_pap_papid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pap',
            name='PAPID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
