# Generated by Django 4.1.2 on 2022-12-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0019_alter_pap_papid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitation',
            name='livelihoodSupportPhotograph',
            field=models.ImageField(blank=True, null=True, upload_to='rehabitation/livelihoodSupportPhotograph/'),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='tenamentsPhotograph',
            field=models.ImageField(blank=True, null=True, upload_to='rehabitation/tenamentsPhotograph/'),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='trainingPhotograph',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='rehabitation/trainingPhotograph/'),
        ),
    ]
