# Generated by Django 4.1.2 on 2022-12-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0020_alter_rehabilitation_livelihoodsupportphotograph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitation',
            name='isCommunityEngagement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='isRelocationAllowance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='isfinancialSupport',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
