# Generated by Django 4.1.2 on 2022-12-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0021_alter_rehabilitation_iscommunityengagement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitation',
            name='RelocationAllowanceAmount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='financialSupportAmount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='shiftingAllowanceAmount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
