# Generated by Django 4.1.2 on 2022-12-31 09:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0022_alter_rehabilitation_relocationallowanceamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabilitation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
