# Generated by Django 4.1.2 on 2023-01-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0023_rehabilitation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsitedetails',
            name='constructionSiteID',
            field=models.CharField(blank=True, choices=[('KT-01', 'KT-01'), ('BY-02', 'BY-02'), ('BPY-03', 'BPY-03'), ('KC-04', 'KC-04'), ('GT-05', 'GT-05')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='constructionSiteName',
            field=models.CharField(blank=True, choices=[('Kolshet Thane', 'Kolshet Thane'), ('BKC Yard', 'BKC Yard'), ('Bhakti Park Yard', 'Bhakti Park Yard'), ('Kavsar Casting', 'Kavsar Casting'), ('Gaimukh Thane', 'Gaimukh Thane')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='LabourCampID',
            field=models.CharField(blank=True, choices=[('KT-01', 'KT-01'), ('BY-02', 'BY-02'), ('BPY-03', 'BPY-03'), ('KC-04', 'KC-04'), ('GT-05', 'GT-05')], max_length=255, null=True),
        ),
    ]
