# Generated by Django 4.1.2 on 2023-01-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0024_constructionsitedetails_constructionsiteid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='quarter',
            field=models.CharField(blank=True, choices=[('January-March', 'January-March'), ('April-June', 'April-June'), ('July-September', 'July-September'), ('October-December', 'October-December')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='labourCampName',
            field=models.CharField(blank=True, choices=[('Kolshet Thane', 'Kolshet Thane'), ('BKC Yard', 'BKC Yard'), ('Bhakti Park Yard', 'Bhakti Park Yard'), ('Kavsar Casting', 'Kavsar Casting'), ('Gaimukh Thane', 'Gaimukh Thane')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='quarter',
            field=models.CharField(blank=True, choices=[('January-March', 'January-March'), ('April-June', 'April-June'), ('July-September', 'July-September'), ('October-December', 'October-December')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pap',
            name='quarter',
            field=models.CharField(blank=True, choices=[('January-March', 'January-March'), ('April-June', 'April-June'), ('July-September', 'July-September'), ('October-December', 'October-December')], max_length=255, null=True),
        ),
    ]
