# Generated by Django 4.1.5 on 2023-01-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0025_alter_constructionsitedetails_quarter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pap',
            old_name='GovernmentLand',
            new_name='governmentLand',
        ),
    ]
