# Generated by Django 4.1.5 on 2023-01-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0026_rename_governmentland_pap_governmentland'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructionsitedetails',
            old_name='isDemarkingOfPathwaysCheck',
            new_name='isDemarkationOfPathways',
        ),
        migrations.RenameField(
            model_name='constructionsitedetails',
            old_name='isDrinkingWaterCheck',
            new_name='isDrinkingWater',
        ),
        migrations.RenameField(
            model_name='constructionsitedetails',
            old_name='isSignagesLabelingCheck',
            new_name='isSignagesLabeling',
        ),
        migrations.RemoveField(
            model_name='constructionsitedetails',
            name='isToiletFacility',
        ),
        migrations.RemoveField(
            model_name='constructionsitedetails',
            name='photographs',
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='availabilityOfDoctorCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='availabilityOfDoctorPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='constructionSite/AvailabilityOfDoctor_photographs/'),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='availabilityOfDoctorRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='demarkationOfPathwaysCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='demarkationOfPathwaysPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='constructionSite/demarkingPathways_photographs/'),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='demarkationOfPathwaysRemark',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='drinkingWaterCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='drinkingWaterPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='constructionSite/drinkingWater_photographs/'),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='drinkingWaterRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='firstAidKitCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='firstAidKitPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='constructionSite/FirstAidKit_photographs/'),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='firstAidKitRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='genralphotographs',
            field=models.ImageField(blank=True, null=True, upload_to='constructionSite/genral_photograph/'),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='isToilet',
            field=models.BooleanField(blank=True, default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='regularHealthCheckupCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='regularHealthCheckupPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='constructionSite/RegularHealthCheckup_Photographs/'),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='regularHealthCheckupRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='signagesLabelingCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='signagesLabelingPhotographs',
            field=models.ImageField(blank=True, null=True, upload_to='constructionSite/signagesLabeling_Photographs/'),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='signagesLabelingRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='toiletCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='toiletPhotograph',
            field=models.ImageField(blank=True, null=True, upload_to='constructionSite/toilet_photographs/'),
        ),
        migrations.AddField(
            model_name='constructionsitedetails',
            name='toiletRemarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='constructionSite/documents/'),
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='isAvailabilityOfDoctor',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='isFirstAidKit',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='isRegularHealthCheckup',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='demarkationOfPathwaysCondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=255, null=True),
        ),
    ]
