# Generated by Django 4.1.5 on 2023-01-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0027_rename_isdemarkingofpathwayscheck_constructionsitedetails_isdemarkationofpathways_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='isToilet',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
    ]
