# Generated by Django 4.1.5 on 2023-01-04 13:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0029_labourcampdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourcampdetails',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='labourcampdetails',
            name='longitude',
        ),
        migrations.AddField(
            model_name='labourcampdetails',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
