# Generated by Django 4.1.5 on 2023-01-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0031_remove_pap_governmentland_remove_pap_privateland'),
    ]

    operations = [
        migrations.AddField(
            model_name='pap',
            name='filledBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
