# Generated by Django 4.1.5 on 2023-01-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0035_remove_rehabilitation_istenaments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labourcamp',
            old_name='segregationOfwasteCondition',
            new_name='segregationOfWasteCondition',
        ),
        migrations.RenameField(
            model_name='labourcamp',
            old_name='segregationOfwastePhotographs',
            new_name='segregationOfWastePhotographs',
        ),
        migrations.RenameField(
            model_name='labourcamp',
            old_name='segregationOfwasteRemarks',
            new_name='segregationOfWasteRemarks',
        ),
    ]
