# Generated by Django 4.1.5 on 2023-01-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0036_rename_segregationofwastecondition_labourcamp_segregationofwastecondition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labourcamp',
            old_name='GenralPhotographs',
            new_name='photographs',
        ),
    ]
