# Generated by Django 4.1.5 on 2023-01-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0038_rename_areaofland_pap_areaofasset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rehabilitation',
            old_name='PAPID',
            new_name='ID',
        ),
    ]
