# Generated by Django 4.1.5 on 2023-01-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0039_rename_papid_rehabilitation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabilitation',
            name='PAPID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pap',
            name='PAPID',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
