# Generated by Django 4.1.5 on 2023-01-16 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0040_rehabilitation_papid_alter_pap_papid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pap',
            name='presentPhotograp',
        ),
        migrations.CreateModel(
            name='PAPPhotographs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentPhotograp', models.ImageField(blank=True, null=True, upload_to='PAP/presentphotograph')),
                ('pap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PAP_photograph', to='SocialMonitoring.pap')),
            ],
        ),
    ]
