# Generated by Django 4.1.5 on 2023-01-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0042_pap_presentphotograp_delete_papphotographs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehabilitation',
            name='packages',
        ),
    ]
