# Generated by Django 4.1.5 on 2023-01-23 07:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package08Alignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('descriptio', models.CharField(blank=True, max_length=254, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=24, null=True)),
                ('begin', models.CharField(blank=True, max_length=24, null=True)),
                ('end', models.CharField(blank=True, max_length=24, null=True)),
                ('altitudemo', models.CharField(blank=True, max_length=254, null=True)),
                ('tessellate', models.FloatField(blank=True, null=True)),
                ('extrude', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('draworder', models.FloatField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package 08 alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package09Alignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('descriptio', models.CharField(blank=True, max_length=254, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=24, null=True)),
                ('begin', models.CharField(blank=True, max_length=24, null=True)),
                ('end', models.CharField(blank=True, max_length=24, null=True)),
                ('altitudemo', models.CharField(blank=True, max_length=254, null=True)),
                ('tessellate', models.FloatField(blank=True, null=True)),
                ('extrude', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('draworder', models.FloatField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package 09 alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package10Alignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('descriptio', models.CharField(blank=True, max_length=254, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=24, null=True)),
                ('begin', models.CharField(blank=True, max_length=24, null=True)),
                ('end', models.CharField(blank=True, max_length=24, null=True)),
                ('altitudemo', models.CharField(blank=True, max_length=254, null=True)),
                ('tessellate', models.FloatField(blank=True, null=True)),
                ('extrude', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('draworder', models.FloatField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package 10 alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package11Alignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('descriptio', models.CharField(blank=True, max_length=254, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=24, null=True)),
                ('begin', models.CharField(blank=True, max_length=24, null=True)),
                ('end', models.CharField(blank=True, max_length=24, null=True)),
                ('altitudemo', models.CharField(blank=True, max_length=254, null=True)),
                ('tessellate', models.FloatField(blank=True, null=True)),
                ('extrude', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('draworder', models.FloatField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package 11 alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package12Alignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('descriptio', models.CharField(blank=True, max_length=254, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=24, null=True)),
                ('begin', models.CharField(blank=True, max_length=24, null=True)),
                ('end', models.CharField(blank=True, max_length=24, null=True)),
                ('altitudemo', models.CharField(blank=True, max_length=254, null=True)),
                ('tessellate', models.FloatField(blank=True, null=True)),
                ('extrude', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('draworder', models.FloatField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package 12 alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package54Alignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('descriptio', models.CharField(blank=True, max_length=254, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=24, null=True)),
                ('begin', models.CharField(blank=True, max_length=24, null=True)),
                ('end', models.CharField(blank=True, max_length=24, null=True)),
                ('altitudemo', models.CharField(blank=True, max_length=254, null=True)),
                ('tessellate', models.FloatField(blank=True, null=True)),
                ('extrude', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('draworder', models.FloatField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package 54 alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectAffectedTrees',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('tree_no_field', models.CharField(blank=True, db_column='tree no.', max_length=254, null=True)),
                ('common_nam', models.CharField(blank=True, db_column='common nam', max_length=254, null=True)),
                ('botanical', models.CharField(blank=True, max_length=254, null=True)),
                ('approx_gi', models.CharField(blank=True, db_column='approx. gi', max_length=254, null=True)),
                ('approx_he', models.CharField(blank=True, db_column='approx. he', max_length=254, null=True)),
                ('approx_ag', models.CharField(blank=True, db_column='approx. ag', max_length=254, null=True)),
                ('proposed_a', models.CharField(blank=True, db_column='proposed a', max_length=254, null=True)),
                ('condition', models.CharField(blank=True, max_length=254, null=True)),
                ('survey_dat', models.DateField(blank=True, db_column='survey dat', null=True)),
                ('survey_tim', models.CharField(blank=True, db_column='survey tim', max_length=254, null=True)),
                ('tree_no', models.CharField(blank=True, db_column='tree no', max_length=254, null=True)),
                ('tree_name', models.CharField(blank=True, db_column='tree name', max_length=254, null=True)),
                ('girth_m_field', models.DecimalField(blank=True, db_column='girth (m)', decimal_places=65535, max_digits=65535, null=True)),
                ('approx_1', models.DecimalField(blank=True, db_column='approx. _1', decimal_places=65535, max_digits=65535, null=True)),
                ('canopy_dia', models.DecimalField(blank=True, db_column='canopy dia', decimal_places=65535, max_digits=65535, null=True)),
                ('conditio_1', models.CharField(blank=True, max_length=254, null=True)),
                ('comments', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('proposed_1', models.CharField(blank=True, max_length=254, null=True)),
                ('approx_gir', models.CharField(blank=True, db_column='approx gir', max_length=254, null=True)),
                ('approx_hei', models.CharField(blank=True, db_column='approx hei', max_length=254, null=True)),
                ('approx_age', models.CharField(blank=True, db_column='approx age', max_length=254, null=True)),
                ('field11', models.CharField(blank=True, max_length=254, null=True)),
                ('layer', models.CharField(blank=True, max_length=254, null=True)),
                ('path', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'project affected trees',
                'managed': False,
            },
        ),
    ]
