# Generated by Django 4.1.5 on 2024-01-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0043_noise_monitoringperiod_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noise',
            name='typeOfArea',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
